version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./Database/configdb:/data/configdb
      - ./Database/db:/data/db
  influxdb:
    image: influxdb:latest
    restart: always
    volumes:
      - ./Database/influxdb:/var/lib/influxdb
  vapor:
    image: reaumur/reaumurserver:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./Public:/ReaumurServer/Public
      - ./Resources:/ReaumurServer/Resources
    environment:
        - VAPOR_HOST=0.0.0.0
        - MONGO_HOST=mongo
        - MONGO_PORT=27017
        - INFLUXDB_HOST=influxdb
        - INFLUXDB_PORT=8086
